CREATE TABLE tab_points (
    id BIGSERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    derive DOUBLE PRECISION NOT NULL,
    funID INTEGER NOT NULL,

    CONSTRAINT funID_fk FOREIGN KEY (funID) REFERENCES tabFun (id)
);